name: Run Code Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout Repository
      uses: actions/checkout@v4

    # Python setup and test
    - name: 🛠 Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 🔍 Install Python Dependencies
      run: pip install pytest

    - name: 🧪 Run Python Tests
      run: |
        if ls *.py 1> /dev/null 2>&1; then 
          pytest *.py
        else 
          echo "⚠️ No Python tests found."
        fi

    # C++ setup and test
    - name: 🛠 Set Up C++ Compiler
      run: sudo apt update && sudo apt install -y g++

    - name: 🏗 Compile & Run C++ Tests
      run: |
        if ls *.cpp 1> /dev/null 2>&1; then 
          g++ -o test_exec *.cpp && ./test_exec
        else 
          echo "⚠️ No C++ test files found."
        fi

    # Java setup and test
    - name: 🛠 Set Up Java Compiler
      run: sudo apt update && sudo apt install -y default-jdk

    - name: ☕ Compile & Run Java Tests
      run: |
        if ls *.java 1> /dev/null 2>&1; then 
          javac *.java && java $(basename *.java .java)
        else 
          echo "⚠️ No Java test files found."
        fi

    # JavaScript setup and test (Node.js installation)
    - name: 🛠 Set Up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: 📦 Install JavaScript Dependencies
      run: npm install

    - name: ⚙️ Run JavaScript Tests
      run: |
        if ls *.js 1> /dev/null 2>&1; then 
          node *.js
        else 
          echo "⚠️ No JavaScript test files found."
        fi
